
CREATE TABLE public.attribute (
                                  bit_mask integer NOT NULL,
                                  id integer NOT NULL,
                                  description text NOT NULL,
                                  name text NOT NULL,
                                  type text NOT NULL,
                                  CONSTRAINT attribute_type_check CHECK (((type)::text = ANY ((ARRAY['MENTALITY'::character varying, 'SKILL'::character varying])::text[])))
);



CREATE TABLE public.attribute_level (
                                        level integer NOT NULL,
                                        xp_required bigint NOT NULL,
                                        type TEXT NOT NULL,
                                        CONSTRAINT attribute_level_type_check CHECK (((type)::text = ANY ((ARRAY['MENTALITY'::character varying, 'SKILL'::character varying])::text[])))
);


CREATE TABLE public.main_quest (
                                   attribute1 integer NOT NULL,
                                   attribute2 integer,
                                   exp1 integer NOT NULL,
                                   exp2 integer NOT NULL,
                                   linked_attribute integer NOT NULL,
                                   id bigint NOT NULL,
                                   theme_id bigint NOT NULL,
                                   name TEXT NOT NULL,
                                   npc_name TEXT NOT NULL
);



CREATE TABLE public.main_sub_quest (
                                       attribute1 integer NOT NULL,
                                       attribute2 integer,
                                       exp1 integer NOT NULL,
                                       exp2 integer,
                                       linked_attribute integer NOT NULL,
                                       main_quest_id bigint NOT NULL,
                                       sub_quest_id bigint NOT NULL
);


CREATE TABLE public.quest_theme (
                                    linked_attribute integer NOT NULL,
                                    id bigint NOT NULL,
                                    name TEXT NOT NULL
);



CREATE TABLE public.sub_quest (
                                  id bigint NOT NULL,
                                  action_unit_type TEXT NOT NULL,
                                  confirm_type TEXT NOT NULL,
                                  name TEXT NOT NULL,
                                  CONSTRAINT sub_quest_action_unit_type_check CHECK (((action_unit_type)::text = ANY ((ARRAY['TIME_SECOND'::character varying, 'TIME_MINUTE'::character varying, 'TIME_HOUR'::character varying, 'NUMBER_1'::character varying, 'NUMBER_2'::character varying, 'NUMBER_3'::character varying, 'DISTANCE'::character varying, 'ONCE'::character varying])::text[]))),
                                  CONSTRAINT sub_quest_confirm_type_check CHECK (((confirm_type)::text = ANY ((ARRAY['MOOD_LOG'::character varying, 'PHOTO_LOG'::character varying])::text[])))
);



CREATE TABLE public.nickname_generator (
                                           id bigint NOT NULL,
                                           name text NOT NULL,
                                           type text NOT NULL,
                                           CONSTRAINT nickname_generator_type_check CHECK (((type)::text = ANY ((ARRAY['ADJECTIVE'::character varying, 'NOUN'::character varying])::text[])))
);



ALTER TABLE public.nickname_generator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nickname_generator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE public.terms_and_conditions (
                                             effective_date date NOT NULL,
                                             is_essential boolean NOT NULL,
                                             created_at timestamp(6) without time zone NOT NULL,
                                             id bigint NOT NULL,
                                             updated_at timestamp(6) without time zone NOT NULL,
                                             version text NOT NULL,
                                             provider_type text NOT NULL,
                                             type text NOT NULL,
                                             link text NOT NULL,
                                             CONSTRAINT terms_and_conditions_provider_type_check CHECK (((provider_type)::text = ANY ((ARRAY['SOCIAL'::character varying, 'GUEST'::character varying])::text[]))),
                                             CONSTRAINT terms_and_conditions_type_check CHECK (((type)::text = ANY ((ARRAY['SERVICE_TERMS'::character varying, 'PRIVATE_POLICY'::character varying])::text[])))
);



ALTER TABLE public.terms_and_conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_and_conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE public.tier_level (
                                   level integer NOT NULL,
                                   level_output integer NOT NULL,
                                   xp_required bigint NOT NULL,
                                   grade text NOT NULL,
                                   CONSTRAINT tier_level_grade_check CHECK (((grade)::text = ANY ((ARRAY['BRONZE'::character varying, 'SILVER'::character varying, 'GOLD'::character varying, 'PLATINUM'::character varying, 'DIA'::character varying])::text[])))
);



ALTER TABLE ONLY public.attribute_level
    ADD CONSTRAINT attribute_level_pkey PRIMARY KEY (level, type);


ALTER TABLE ONLY public.attribute
    ADD CONSTRAINT attribute_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT main_quest_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT main_sub_quest_pkey PRIMARY KEY (main_quest_id, sub_quest_id);


ALTER TABLE ONLY public.quest_theme
    ADD CONSTRAINT quest_theme_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.sub_quest
    ADD CONSTRAINT sub_quest_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.terms_and_conditions
    ADD CONSTRAINT terms_and_conditions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nickname_generator
    ADD CONSTRAINT nickname_generator_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nickname_generator
    ADD CONSTRAINT nickname_generator_name_key UNIQUE (name);

ALTER TABLE ONLY public.tier_level
    ADD CONSTRAINT tier_level_pkey PRIMARY KEY (level);

ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fk2al823fkjcpfijlvj74wq0qo6 FOREIGN KEY (theme_id) REFERENCES public.quest_theme(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fk740sr71dphvopwfxhefdscem5 FOREIGN KEY (main_quest_id) REFERENCES public.main_quest(id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fkdg6a71ap6h2hfqeqo65xvjc8i FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fkldpc18stwkst06oci9f7kdiq4 FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fkqhlr95w8xql98e2r487di00qm FOREIGN KEY (attribute2) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fks8vqf0gysv7fqkq7p4qrs5gpn FOREIGN KEY (sub_quest_id) REFERENCES public.sub_quest(id);

ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fksxhip7vuq6l0kebetdy8b0gnm FOREIGN KEY (attribute2) REFERENCES public.attribute(id);
