
CREATE TABLE public.attribute (
                                  bit_mask integer NOT NULL,
                                  default_level integer NOT NULL,
                                  id integer NOT NULL,
                                  description character varying(255) NOT NULL,
                                  name character varying(255) NOT NULL,
                                  type character varying(255) NOT NULL,
                                  CONSTRAINT attribute_type_check CHECK (((type)::text = ANY ((ARRAY['MENTALITY'::character varying, 'SKILL'::character varying])::text[])))
);



CREATE TABLE public.attribute_level (
                                        level integer NOT NULL,
                                        required_exp integer NOT NULL,
                                        type character varying(255) NOT NULL,
                                        CONSTRAINT attribute_level_type_check CHECK (((type)::text = ANY ((ARRAY['MENTALITY'::character varying, 'SKILL'::character varying])::text[])))
);


CREATE TABLE public.main_quest (
                                   attribute1 integer NOT NULL,
                                   attribute2 integer,
                                   exp1 integer NOT NULL,
                                   exp2 integer NOT NULL,
                                   linked_attribute integer NOT NULL,
                                   id bigint NOT NULL,
                                   theme_id bigint NOT NULL,
                                   name character varying(255) NOT NULL,
                                   npc_name character varying(255) NOT NULL
);



CREATE TABLE public.main_sub_quest (
                                       attribute1 integer NOT NULL,
                                       attribute2 integer,
                                       exp1 integer NOT NULL,
                                       exp2 integer,
                                       linked_attribute integer NOT NULL,
                                       main_quest_id bigint NOT NULL,
                                       sub_quest_id bigint NOT NULL
);


CREATE TABLE public.quest_theme (
                                    linked_attribute integer NOT NULL,
                                    id bigint NOT NULL,
                                    name character varying(255) NOT NULL
);



CREATE TABLE public.sub_quest (
                                  id bigint NOT NULL,
                                  action_unit_type character varying(255) NOT NULL,
                                  confirm_type character varying(255) NOT NULL,
                                  name character varying(255) NOT NULL,
                                  CONSTRAINT sub_quest_action_unit_type_check CHECK (((action_unit_type)::text = ANY ((ARRAY['TIME_SECOND'::character varying, 'TIME_MINUTE'::character varying, 'TIME_HOUR'::character varying, 'NUMBER_1'::character varying, 'NUMBER_2'::character varying, 'NUMBER_3'::character varying, 'DISTANCE'::character varying, 'ONCE'::character varying])::text[]))),
    CONSTRAINT sub_quest_confirm_type_check CHECK (((confirm_type)::text= ANY ((ARRAY['MOOD_LOG'::text, 'PHOTO_LOG'::text]))))
);



CREATE TABLE terms_and_conditions (
                                             id bigint NOT NULL,
                                             created_at timestamp(6) without time zone NOT NULL,
                                             effective_date date NOT NULL,
                                             is_essential boolean NOT NULL,
                                             link character varying(2048) NOT NULL,
                                             type character varying(50) NOT NULL,
                                             updated_at timestamp(6) without time zone NOT NULL,
                                             version character varying(20) NOT NULL,
                                             CONSTRAINT terms_and_conditions_type_check CHECK (((type)::text = ANY ((ARRAY['SERVICE_TERMS'::character varying, 'PRIVATE_POLICY'::character varying])::text[])))
);



ALTER TABLE public.terms_and_conditions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_and_conditions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.nickname_generator (
                                           id integer NOT NULL,
                                           type character varying(255) NOT NULL,
                                           name character varying(255) NOT NULL UNIQUE,
                                           CONSTRAINT type_check CHECK (((type)::text = ANY ((ARRAY['ADJECTIVE'::character varying, 'NOUN'::character varying])::text[])))
);


ALTER TABLE public.nickname_generator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nickname_generator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.attribute_level
    ADD CONSTRAINT attribute_level_pkey PRIMARY KEY (level, type);


ALTER TABLE ONLY public.attribute
    ADD CONSTRAINT attribute_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT main_quest_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT main_sub_quest_pkey PRIMARY KEY (main_quest_id, sub_quest_id);


ALTER TABLE ONLY public.quest_theme
    ADD CONSTRAINT quest_theme_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.sub_quest
    ADD CONSTRAINT sub_quest_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.terms_and_conditions
    ADD CONSTRAINT terms_and_conditions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.nickname_generator
    ADD CONSTRAINT nickname_generator_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.terms_and_conditions
    ADD CONSTRAINT ukpecxcojg8duukk3m2x1sojbyl UNIQUE (type, version);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fk2al823fkjcpfijlvj74wq0qo6 FOREIGN KEY (theme_id) REFERENCES public.quest_theme(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fk740sr71dphvopwfxhefdscem5 FOREIGN KEY (main_quest_id) REFERENCES public.main_quest(id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fkdg6a71ap6h2hfqeqo65xvjc8i FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fkldpc18stwkst06oci9f7kdiq4 FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_quest
    ADD CONSTRAINT fkqhlr95w8xql98e2r487di00qm FOREIGN KEY (attribute2) REFERENCES public.attribute(id);


ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fks8vqf0gysv7fqkq7p4qrs5gpn FOREIGN KEY (sub_quest_id) REFERENCES public.sub_quest(id);

ALTER TABLE ONLY public.main_sub_quest
    ADD CONSTRAINT fksxhip7vuq6l0kebetdy8b0gnm FOREIGN KEY (attribute2) REFERENCES public.attribute(id);
