INSERT INTO terms_and_conditions VALUES (
                                            default,
                                            NOW(),
                                            NOW(),
                                            TRUE,
                                            'https://www.notion.so/242b86814a1180eeb5d0ee670aa26aa7?pvs=13',
                                            'SERVICE_TERMS',
                                            NOW(),
                                            '1.0.0'
                                        ),
                                        (
                                            default,
                                            NOW(),
                                            NOW(),
                                            TRUE,
                                            'https://www.notion.so/244b86814a118059abf1c4995f3cd78a',
                                            'PRIVATE_POLICY',
                                            NOW(),
                                            '1.0.0'
                                        );